services:
  app:
    build: .
    container_name: fila-conf-app   
    restart: unless-stopped
    ports:
      - '3000:3000'
      - '5555:5555'
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      DATABASE_URL: postgresql://postgres:postgres@db:5432/fila_conferencia
      CHOKIDAR_USEPOLLING: 'true'
    command: sh -c "npm install && npx prisma generate && npm run start:dev"
    depends_on:
      - db

  db:
    image: postgres:15
    container_name: fila-conf-postgres
    restart: always
    ports:
    - "5433:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: fila_conferencia
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
